const PDFDocument = require('pdfkit');
const { renderTimesheetPage } = require('../timesheetController');

// Count PDF page objects in the generated bytes.
function countPages(buf) {
    // PDFKit emits one "/Type /Page" (not /Pages) object per page.
    const matches = buf.toString('latin1').match(/\/Type\s*\/Page[^s]/g);
    return matches ? matches.length : 0;
}

function renderToBuffer(ts) {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ size: 'LETTER', layout: 'landscape', margins: { top: 14, bottom: 14, left: 14, right: 14 } });
        const chunks = [];
        doc.on('data', (c) => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);
        renderTimesheetPage(doc, ts);
        doc.end();
    });
}

function entry(dayOfWeek, dateOfService) {
    return {
        dayOfWeek,
        dateOfService,
        adlActivities: JSON.stringify({ Bathing: true, Dressing: true, Eating: true }),
        iadlActivities: JSON.stringify({ Laundry: true, Shopping: true }),
        respiteActivities: JSON.stringify({ Companionship: true, 'Safety Supervision': true }),
        companionActivities: JSON.stringify({ Companionship: true, 'Social Activities': true }),
        adlHours: 2, iadlHours: 1, respiteHours: 1, companionHours: 1,
        adlTimeIn: '08:00', adlTimeOut: '10:00',
        iadlTimeIn: '10:00', iadlTimeOut: '11:00',
        respiteTimeIn: '11:00', respiteTimeOut: '12:00',
        companionTimeIn: '12:00', companionTimeOut: '13:00',
        adlPcaInitials: 'AB', adlClientInitials: 'DW',
        iadlPcaInitials: 'AB', iadlClientInitials: 'DW',
        respitePcaInitials: 'AB', respiteClientInitials: 'DW',
        companionPcaInitials: 'AB', companionClientInitials: 'DW',
    };
}

function makeTimesheet() {
    const entries = [];
    for (let d = 0; d < 7; d++) {
        entries.push(entry(d, `2026-07-${String(26 + d).padStart(2, '0')}`));
    }
    return {
        id: 1,
        weekStart: '2026-07-26',
        status: 'submitted',
        submittedAt: '2026-08-02T12:00:00Z',
        pcaName: 'Test PCA',
        completionDate: '08/01/2026',
        client: { clientName: 'Diane Wilson', medicaidId: '1234567890' },
        totalHours: 35, totalPasHours: 14, totalHmHours: 7, totalRespiteHours: 7, totalCompanionHours: 7,
        entries,
    };
}

function renderMultiToBuffer(timesheets) {
    const { renderTimesheetPage: render } = require('../timesheetController');
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ size: 'LETTER', layout: 'landscape', margins: { top: 14, bottom: 14, left: 14, right: 14 } });
        const chunks = [];
        doc.on('data', (c) => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);
        // Mirrors exportBulkTimesheetPdf
        for (let i = 0; i < timesheets.length; i++) {
            if (i > 0) doc.addPage();
            render(doc, timesheets[i]);
        }
        doc.end();
    });
}

describe('timesheet PDF pagination', () => {
    it('renders a full four-section timesheet on a single page (no blank-page explosion)', async () => {
        const buf = await renderToBuffer(makeTimesheet());
        expect(countPages(buf)).toBe(1);
    });

    it('renders a normal two-section timesheet on a single page', async () => {
        const ts = makeTimesheet();
        // Strip Respite + Companion so only PAS + Homemaker render.
        ts.totalRespiteHours = 0;
        ts.totalCompanionHours = 0;
        ts.entries = ts.entries.map(e => ({
            ...e,
            respiteActivities: '{}', companionActivities: '{}',
            respiteHours: 0, companionHours: 0,
        }));
        const buf = await renderToBuffer(ts);
        expect(countPages(buf)).toBe(1);
    });

    it('bulk export produces exactly one page per timesheet', async () => {
        const sheets = [makeTimesheet(), makeTimesheet(), makeTimesheet()];
        const buf = await renderMultiToBuffer(sheets);
        expect(countPages(buf)).toBe(3);
    });
});
