-- CreateTable
CREATE TABLE "leads" (
    "id" SERIAL NOT NULL,
    "first_name" TEXT NOT NULL DEFAULT '',
    "last_name" TEXT NOT NULL DEFAULT '',
    "phone" TEXT NOT NULL DEFAULT '',
    "alternate_phone" TEXT NOT NULL DEFAULT '',
    "address" TEXT NOT NULL DEFAULT '',
    "dob" TIMESTAMP(3),
    "gender" TEXT NOT NULL DEFAULT '',
    "medicaid_id" TEXT NOT NULL DEFAULT '',
    "insurance_number" TEXT NOT NULL DEFAULT '',
    "insurance_type" TEXT NOT NULL DEFAULT '',
    "referral_source" TEXT NOT NULL DEFAULT '',
    "doctor_name" TEXT NOT NULL DEFAULT '',
    "doctor_phone" TEXT NOT NULL DEFAULT '',
    "caseworker_name" TEXT NOT NULL DEFAULT '',
    "caseworker_phone" TEXT NOT NULL DEFAULT '',
    "emergency_contact_name" TEXT NOT NULL DEFAULT '',
    "emergency_contact_relation" TEXT NOT NULL DEFAULT '',
    "emergency_contact_phone" TEXT NOT NULL DEFAULT '',
    "emergency_contact_email" TEXT NOT NULL DEFAULT '',
    "call_notes" TEXT NOT NULL DEFAULT '',
    "services_requested" TEXT NOT NULL DEFAULT '[]',
    "days_per_week" TEXT NOT NULL DEFAULT '',
    "hours_per_day" TEXT NOT NULL DEFAULT '',
    "start_date_needed" TEXT NOT NULL DEFAULT '',
    "case_type" TEXT NOT NULL DEFAULT 'initial',
    "auth_status" TEXT NOT NULL DEFAULT '',
    "expected_start_date" TIMESTAMP(3),
    "current_agency_name" TEXT NOT NULL DEFAULT '',
    "current_auth_hours_month" INTEGER NOT NULL DEFAULT 0,
    "auth_number" TEXT NOT NULL DEFAULT '',
    "transfer_reason" TEXT NOT NULL DEFAULT '',
    "transfer_notes" TEXT NOT NULL DEFAULT '',
    "pp_rate" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "pp_hours_per_week" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "pp_deposit_hours" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "gender_preference" TEXT NOT NULL DEFAULT 'No preference',
    "age_preference" TEXT NOT NULL DEFAULT 'No preference',
    "shift_preferences" TEXT NOT NULL DEFAULT '[]',
    "language_preference" TEXT NOT NULL DEFAULT 'English',
    "schedule_notes" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'new',
    "assigned_to" TEXT NOT NULL DEFAULT '',
    "follow_up_date" TIMESTAMP(3),
    "converted_client_id" INTEGER,
    "converted_at" TIMESTAMP(3),
    "archived_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "leads_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "leads_status_idx" ON "leads"("status");
